### ISSUE TITLE
hyp_dictionary  endless loop in one to many relationship

### ISSUE THREAD

**Issue by RolandasRazma** [SyncDB/SYNCPropertyMapper#128]
mo.hyp_dictionary(using: .array) loops endlessly if object have relationship. I guess it makes sense, but I think hyp_dictionary shouldn't go deeper than 1 level

Attaching backtrace

[bt.txt](https://github.com/SyncDB/NSManagedObject-HYPPropertyMapper/files/513485/bt.txt)

**Comment by 3lvis** [comment]
In some cases this might be expected behavior.

Maybe you can relate to this issue.

https://github.com/SyncDB/NSManagedObject-HYPPropertyMapper/issues/112

Let me know if this is something else.

I could double check if you could provide an screenshot of your Core Data model and an example of your JSON file.

**Comment by 3lvis** [comment]
Closing this for lack of more information. I really think this is related to #112 and can be solved by adding `hyper.nonExportable`.
