### ISSUE TITLE
Support for code tables 

### ISSUE THREAD

**Issue by kostiakoval** [SyncDB/SYNCPropertyMapper#44]
I want to have custom type mapping. From String to Int, 

Example: 
I want this object to maps

```
This JSON
{
  "organization_type": "Company"
}

To that object

@interface object  : NSManagedObject {}
@property (nonatomic, strong) NSNumber* organizationType;
@end
```

"Company" -> 0
"Region" -> 1

I think the mapping logic should be implemented by users, in the callback fuction or some params

**Comment by NSElvis** [comment]
@kostiakoval: I've had this use case before, I think the structure is called `code tables`. 

I guess the proper structure for this would be

```json
  "organization_type": {
      "id":  0,
      "name":  "Company"
}
```

Right?

**Comment by NSElvis** [comment]
I really like this idea, we've had a similar requirement in our project, we ended un handling it "internally".

**Comment by 3lvis** [comment]
I think the ideal thing would be adding `hyper.codeTable` to User Info in the `organizationType` attribute.

![screen shot 2015-04-07 at 12 47 51 am](https://cloud.githubusercontent.com/assets/1088217/7014035/c88d375e-dcbf-11e4-96d1-db07e1c262c3.png)

Value: `0:"Company", 1:"Region", 2:"Country", 4:"Continent"`

When running `mogenerator` this will generate something like this:

```objc
typedef NS_ENUM(NSInteger, HYPContractType) {
    HYPCompanyOrganizationType = 0,
    HYPRegionOrganizationType = 1,
    HYPCountryOrganizationType = 2,
    HYPContinentOrganizationType = 4
};
```

When filling with JSON, if the value is a `string` and the attribute is a `NSNumber` we will look for the `codeTable`. If we find it, we will map to the NSNumber value instead of the `NSString`.

**Comment by kostiakoval** [comment]
sounds good. only 1 think I don't like specifying those attributes in CoreData Info, it's quite hard and not convenient. 

Why should you make those limitation (if the value is a string)
if code table existing just map them. 
[COMPANY_PREFIX][VALUE][ATTRIBUTE_NAME]  - I'm not sure I get this one but general ides is very good.

**Comment by 3lvis** [comment]
@kostiakoval Do you have an alternative? I proposed this because in this way is easy to read it by both mogenerator and Sync/PropertyMapper.

```
COMPANY_PREFIX = HYP
VALUE = Region
ATTRIBUTE_NAME = OrganizationType
KEY = 0
```

**Comment by 3lvis** [comment]
Some of this could be done using Deep mapping. Closing.

https://github.com/SyncDB/SYNCPropertyMapper#deep-mapping
